version: '1.0'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    image: redis:5-alpine

  web:
    build:
      ./testcase/
    depends_on:
      - db
    env_file:
      - ./.env

  celery:
    build: ./testcase/
    command: celery worker --app=core --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    depends_on:
      - web
      - redis
      - db

  dashboard:
    build: ./testcase/
    command: flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery