version: '1.0'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:5-alpine

  web:
    build:
      ./testcase/
    restart: on-failure
    volumes:
      - ./testcase:/testcase
    depends_on:
      - db
    env_file:
      - .env

  celery:
    build: ./testcase/
    hostname: celery
    links:
      - redis
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./testcase:/testcase
    depends_on:
      - redis
      - db
